/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 optimized-room.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three';
export function Room(props) {
  return null; // Disabled for deployment
}

// useGLTF.preload('./assets/public/models/optimized-room.glb')
